//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurucuKursuOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genel_LOG
    {
        public int LOG_ID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Adi_Soyadi { get; set; }
        public string islemTarihi { get; set; }
        public string Mesaj { get; set; }
        public string StackTrace { get; set; }
    }
}
