//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurucuKursuOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KursiyerBelgeKayit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KursiyerBelgeKayit()
        {
            this.KursiyerSinavKayit = new HashSet<KursiyerSinavKayit>();
        }
    
        public int KBID { get; set; }
        public int Kursiyer_ID { get; set; }
        public Nullable<int> SurucuBelgesi_ID { get; set; }
        public string Kayıt_Tarih { get; set; }
        public Nullable<int> Donem_ID { get; set; }
        public Nullable<int> KaydedenKullanici_ID { get; set; }
    
        public virtual Donem Donem { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kursiyer Kursiyer { get; set; }
        public virtual SurucuBelgesiTuru SurucuBelgesiTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KursiyerSinavKayit> KursiyerSinavKayit { get; set; }
    }
}
