//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurucuKursuOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KursiyerBakiye
    {
        public int KursiyerBakiye_ID { get; set; }
        public Nullable<int> Odenen { get; set; }
        public Nullable<int> Kursiyer_ID { get; set; }
        public Nullable<int> Borc { get; set; }
    
        public virtual Kursiyer Kursiyer { get; set; }
    }
}
