//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurucuKursuOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kursiyer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kursiyer()
        {
            this.DireksiyonDersiKayit = new HashSet<DireksiyonDersiKayit>();
            this.KursiyerBakiye = new HashSet<KursiyerBakiye>();
            this.KursiyerBelgeKayit = new HashSet<KursiyerBelgeKayit>();
            this.KursiyerOdeme = new HashSet<KursiyerOdeme>();
            this.KursiyerSinavKayit = new HashSet<KursiyerSinavKayit>();
        }
    
        public int Kursiyer_ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string DogumTarih { get; set; }
        public string TC { get; set; }
        public string Adres { get; set; }
        public string OgrenimDurumu { get; set; }
        public Nullable<bool> AdliBelge { get; set; }
        public string Telefon { get; set; }
        public Nullable<bool> SaglikRaporu { get; set; }
        public string KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireksiyonDersiKayit> DireksiyonDersiKayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KursiyerBakiye> KursiyerBakiye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KursiyerBelgeKayit> KursiyerBelgeKayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KursiyerOdeme> KursiyerOdeme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KursiyerSinavKayit> KursiyerSinavKayit { get; set; }
    }
}
