//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurucuKursuOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KursiyerSinavKayit
    {
        public int KursiyerSinav_ID { get; set; }
        public Nullable<int> Kursiyer_ID { get; set; }
        public Nullable<int> Sinav_ID { get; set; }
        public string Kayitzamani { get; set; }
        public Nullable<int> KaydedenKullanici_ID { get; set; }
        public Nullable<int> KursiyerBelgeKayit_ID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kursiyer Kursiyer { get; set; }
        public virtual KursiyerBelgeKayit KursiyerBelgeKayit { get; set; }
        public virtual Sinav Sinav { get; set; }
    }
}
