//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurucuKursuOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_Sil
    {
        public int Sil_ID { get; set; }
        public Nullable<int> ID { get; set; }
        public string adiSoyadi { get; set; }
        public string TC { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string SilenKisi { get; set; }
        public string silmeTarihi { get; set; }
    }
}
