//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurucuKursuOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK_Bilgileri
    {
        public int ID { get; set; }
        public string SK_Adi { get; set; }
        public string SK_Adress { get; set; }
        public string SK_Telefon { get; set; }
    }
}
